# Generated by Django 6.0.3 on 2026-03-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_place_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelproject',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='travelproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
